/**
 * Rebalancer (Exec Bot) agent
 *
 * Executes pending rebalance orders generated by the Managing Partner.
 * Sells overweight positions first (to free cash), then buys underweight.
 * Logs all trades to trade history.
 */
import { connect, disconnect, placeMarketOrder } from '../connection/gateway.js';
import { RebalanceOrder } from '../allocation/portfolio.js';
import { loadState, saveState, appendTrade } from '../state/store.js';
import { log, logError } from '../log.js';

const AGENT = 'Rebalancer';

async function run(): Promise<void> {
  log('Checking for pending rebalance orders', AGENT);

  const state = loadState();
  const orders = state.pendingOrders as RebalanceOrder[] | undefined;

  if (!orders || orders.length === 0) {
    log('No pending orders — nothing to do', AGENT);
    return;
  }

  log(`${orders.length} pending order(s) to execute`, AGENT);
  await connect();

  try {
    // Execute sells first, then buys
    const sells = orders.filter(o => o.action === 'SELL');
    const buys = orders.filter(o => o.action === 'BUY');

    for (const order of [...sells, ...buys]) {
      try {
        log(`Executing: ${order.action} ${order.qty} ${order.symbol} (~$${order.estimatedValue})`, AGENT);
        const result = await placeMarketOrder(order.symbol, order.action, order.qty);
        log(`Filled: ${result.action} ${result.qty} ${result.symbol} (orderId=${result.orderId}, status=${result.status})`, AGENT);

        appendTrade({
          timestamp: new Date().toISOString(),
          symbol: order.symbol,
          action: order.action,
          qty: order.qty,
          estimatedValue: order.estimatedValue,
          orderId: result.orderId,
          status: result.status,
          reason: order.reason,
        });
      } catch (err) {
        logError(`Failed to execute ${order.action} ${order.qty} ${order.symbol}`, err, AGENT);
      }
    }

    // Clear pending orders
    state.pendingOrders = [];
    state.lastRebalanceAt = new Date().toISOString();
    saveState(state);
    log('Rebalance complete', AGENT);

  } finally {
    disconnect();
  }
}

const isOnce = process.argv.includes('--once');
run()
  .then(() => { if (isOnce) process.exit(0); })
  .catch((err) => { logError('Fatal', err, AGENT); process.exit(1); });
